[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "changemakers"
version = "0.0.1"
description = "Mobile API for Changemakers"
authors = [
    {name = "Arunodhaya"}
]
# This line tells Frappe Cloud this app works with Frappe v15
dependencies = [
    "frappe>=15.0.0,<16.0.0"
]

[tool.flit.module]
name = "changemakers"